# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default=b'21:25:02.412172', max_length=20),
        ),
    ]
