# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161019_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_delivery_time', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('last_delivery_time', models.DecimalField(decimal_places=2, default=18.0, max_digits=4)),
                ('deliveries_per_hour', models.IntegerField(default=2, max_length=2)),
            ],
        ),
    ]
