# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliveries_per_hour',
            field=models.IntegerField(default=2),
        ),
    ]
