# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20161020_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='deliveries_per_hour',
            new_name='delvs_per_hour',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='first_delivery_time',
            new_name='f_delivery_time',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='last_delivery_time',
            new_name='l_delivery_time',
        ),
    ]
